### PR TITLE
Avoid `ERR_INVALID_ARG_TYPE` if `APALACHE_DIST` is not set

### LINKED ISSUE #905: `quint verify` is crashes with `ERR_INVALID_ARG_TYPE` when APALACHE_DIST is not set
```

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1176:7)
    at findApalacheDistribution (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/quintVerifier.js:82:26)
    at verify (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/quintVerifier.js:173:36)
    at verifySpec (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/cliCommands.js:437:39)
    at EitherConstructor.asyncChain (/home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:114:16)
    at /home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/cli.js:33:39 {
  code: 'ERR_INVALID_ARG_TYPE'
}

quint/quint on  main [$?] is 📦 v0.10.0 via  v19.6.0 
x  echo $APALACHE_DIST 
```

### PR DESCRIPTION
**Pull request by thpani**
Fix an issue where `quint verify` crashes with `ERR_INVALID_ARG_TYPE` when `APALACHE_DIST` is not set.

Closes #905

### CODE REVIEW

File: quint/src/quintVerifier.ts [hunk 1]
```diff
@@ -142,30 +142,33 @@ function err<A>(explanation: string, errors: ErrorMessage[] = [], traces?: ItfTr
 }
 
 function findApalacheDistribution(): VerifyResult<ApalacheDist> {
-  const configuredDist =
-    process.env.APALACHE_DIST && path.isAbsolute(process.env.APALACHE_DIST)
-      ? process.env.APALACHE_DIST
-      : path.join(process.cwd(), process.env.APALACHE_DIST!)
-
-  // TODO: fetch release if APALACHE_DIST is not configured
-  // See https://github.com/informalsystems/quint/issues/701
```
Comment (shonfeder) [inline quint/src/quintVerifier.ts:151]: Can we keep this TODO, it is still relevant.

File: quint/src/quintVerifier.ts [hunk 2]
```diff
@@ -142,30 +142,33 @@ function err<A>(explanation: string, errors: ErrorMessage[] = [], traces?: ItfTr
...
+  if (!fs.existsSync(dist)) {
+    return err(`Specified APALACHE_DIST ${dist} does not exist.`)
+  }
+
+  const jar = path.join(dist, 'lib', 'apalache.jar')
+  const exe = path.join(dist, 'bin', 'apalache-mc')
+
+  if (!fs.existsSync(jar)) {
+    return err(
+      `Apalache distribution is corrupted: cannot find ${jar}. Ensure the APALACHE_DIST environment variable is set.`
```
Comment (shonfeder) [inline quint/src/quintVerifier.ts:162]: iiuc, we should already know at this point whether the envvar is set:

```suggestion
      `Apalache distribution is corrupted: cannot find ${jar}.`
```

File: quint/src/quintVerifier.ts [hunk 3]
```diff
@@ -142,30 +142,33 @@ function err<A>(explanation: string, errors: ErrorMessage[] = [], traces?: ItfTr
...
+    )
+  }
+  if (!fs.existsSync(exe)) {
+    return err(
+      `Apalache distribution is corrupted: cannot find ${exe}. Ensure the APALACHE_DIST environment variable is set.`
```
Comment (shonfeder) [inline quint/src/quintVerifier.ts:167]:
```suggestion
      `Apalache distribution is corrupted: cannot find ${exe}.`
```

**Comment by shonfeder** [comment]
Thanks for the fix!

File: quint/src/quintVerifier.ts (hunk 1 above)
Comment (thpani) [reply quint/src/quintVerifier.ts:151]: Ah, sorry, overlooked this in the diff! Restored in 4234a021

File: quint/src/quintVerifier.ts (hunk 2 above)
Comment (thpani) [reply quint/src/quintVerifier.ts]: Good catch! Meant to rephrase the second sentence: 739ced81

**Review by shonfeder — APPROVED** [review]
