### PR TITLE
Enumerate range set for picking MapSet values

### LINKED ISSUE #1530: An `index out of range` bug when combining `oneOf` and `setOfMaps`
Consider the following simple model:
```
module problem{
    var x: str -> (str -> int)
    val X = Set("A", "B")
    val Y = Set("C", "D")
    val Z = Set(1,2)
    val allPossibleVals = setOfMaps(X, setOfMaps(Y, Z))

    action init =                 
        nondet initVal = allPossibleVals.oneOf()
        x' = initVal

    action step = 
        x' = x

    }   
```
When running the simulator `quint run --max-samples=1 --max-steps=1 problem.qnt`, a runtime error occurs: 

> error: [QNT501] Index out of bounds
> [lineNumber]:         nondet initVal = allPossibleVals.oneOf()

---

There are two curious things here:
1. If we modify `Y` to be a singleton set, the problem disappears. (Making `X` or `Z` singleton has no effect.)
2. If the set `allPossibleVals` is evaluated first (in the REPL) and the provided as a constant to the model, the problem disappears.
Concretely: 
```
module problem{
    var x: str -> (str -> int)
    val allPossibleVals = Set(
        Map("A" -> Map("C" -> 1, "D" -> 1), "B" -> Map("C" -> 1, "D" -> 1)),
        Map("A" -> Map("C" -> 2, "D" -> 1), "B" -> Map("C" -> 1, "D" -> 1)),
        Map("A" -> Map("C" -> 1, "D" -> 2), "B" -> Map("C" -> 1, "D" -> 1)),
        Map("A" -> Map("C" -> 2, "D" -> 2), "B" -> Map("C" -> 1, "D" -> 1)),
        Map("A" -> Map("C" -> 1, "D" -> 1), "B" -> Map("C" -> 2, "D" -> 1)),
        Map("A" -> Map("C" -> 2, "D" -> 1), "B" -> Map("C" -> 2, "D" -> 1)),
        Map("A" -> Map("C" -> 1, "D" -> 2), "B" -> Map("C" -> 2, "D" -> 1)),
        Map("A" -> Map("C" -> 2, "D" -> 2), "B" -> Map("C" -> 2, "D" -> 1)),
        Map("A" -> Map("C" -> 1, "D" -> 1), "B" -> Map("C" -> 1, "D" -> 2)),
        Map("A" -> Map("C" -> 2, "D" -> 1), "B" -> Map("C" -> 1, "D" -> 2)),
        Map("A" -> Map("C" -> 1, "D" -> 2), "B" -> Map("C" -> 1, "D" -> 2)),
        Map("A" -> Map("C" -> 2, "D" -> 2), "B" -> Map("C" -> 1, "D" -> 2)),
        Map("A" -> Map("C" -> 1, "D" -> 1), "B" -> Map("C" -> 2, "D" -> 2)),
        Map("A" -> Map("C" -> 2, "D" -> 1), "B" -> Map("C" -> 2, "D" -> 2)),
        Map("A" -> Map("C" -> 1, "D" -> 2), "B" -> Map("C" -> 2, "D" -> 2)),
        Map("A" -> Map("C" -> 2, "D" -> 2), "B" -> Map("C" -> 2, "D" -> 2))
    )

    action init = 
        nondet initVal = allPossibleVals.oneOf()
        x' = initVal

    action step = 
        x' = x

    }
```

### LINKED ISSUE #1736: Spurious error in the Quint simulator
I have run into a strange issue with the Quint simulator. Here is an MWE:

```bluespec
module t {
    val A = Set("a", "b", "c")
    val B = Set(2, 3, 4)
    val C = Set("x", "y")

    var myMap2: str -> (int -> str)

    action init = {
        nondet _foo = A.setOfMaps(B.setOfMaps(C)).oneOf()
        myMap2' = _foo
    }

    action step = all {
        myMap2' = myMap2,
    }

    val inv = myMap2.keys() == A
}
```

The command `quint verify` works:

```sh
quint verify --invariant=inv t.qnt
[ok] No violation found (134ms).
```

The command `quint run` fails:

```sh
quint run --invariant=inv t.qnt
.../t.qnt:10:38 - error: [QNT501] Index out of bounds](t.qnt:10:19 - error: [QNT501] Index out of bounds)
10:         myMap2' = _foo
```

It looks like the simulator fails somewhere in `oneOf`.

### PR DESCRIPTION
**Pull request by bugarela**
Hello :octocat: 

This fixes #1530 and fixes #1736 (duplicated).

This is not the most performative solution as it forces enumeration, but it's better then breaking which is the current state.

- [X] I have read and I understand the [Note on AI-assisted contributions](https://github.com/informalsystems/quint/blob/main/CONTRIBUTING.md#note-on-ai-assisted-contributions)
- [X] Changes manually tested locally and confirmed to work as described
      (including screenshots is helpful)
- [X] Tests added for any new code
- [ ] Documentation added for any new functionality
- [ ] Entries added to the respective `CHANGELOG.md` for any new functionality

### CODE REVIEW

File: quint/src/runtime/impl/runtimeValue.ts [hunk 1]
```diff
@@ -1559,7 +1559,14 @@ class RuntimeValueMapSet extends RuntimeValueBase implements RuntimeValue {
...
     for (const key of this.domainSet) {
-      const valueOrNone = this.rangeSet.pick(positions)
+      // enumerate the range set to avoid issues like #1530
+      const elems: RuntimeValue[] = []
+      for (const i of this) {
+        elems.push(i)
+      }
+      const rangeSet = new RuntimeValueSet(Set(elems))
+
+      const valueOrNone = rangeSet.pick(positions)
```
Comment (konnov) [inline quint/src/runtime/impl/runtimeValue.ts:1573]: I have not been looking at this code for long time. Could the issue be that `positions` is a mutable iterator, and it gets corrupted in nested calls? It probably needs to be copied or something like that.
